CREATE DATABASE LMS;

USE LMS;

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BOOKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    AVAILABLE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    BOOK_ID INT,
    TYPE ENUM('borrow', 'return'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE SET NULL
);

ALTER TABLE BOOKS ADD COLUMN GENRE VARCHAR(255) default 'N/A';

ALTER TABLE BOOKS ADD COLUMN isbn VARCHAR(255) default 'N/A';

ALTER TABLE USERS ADD COLUMN ROLE ENUM('admin', 'user') DEFAULT 'user';

ALTER TABLE USERS ADD COLUMN PASSWORD VARCHAR(255);